pycodestyle:
        max-line-length: 120 # Default is 79 in PEP8
        ignore:
            - I0011
            - C0302
            - C0111
            - R0801
            - R0902
            - R0904
            - R0912
            - R0913
            - R0914
            - R0915
            - R0921
            - R0922
            - W0142
            - W0403
            - W0603
            - C1001
            - W0121
            - useless-else-on-loop
            - bad-whitespace
            - unpacking-non-sequence
            - superfluous-parens
            - cyclic-import
            - no-else-return
            - len-as-condition
            - too-many-boolean-expressions
